name: Build and Push Docker Image

on:
  push:
    branches:
      - prod

env:
  REGISTRY_NAME: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository  | toLower }}  # This will be in the format "owner/repo"
  IMAGE_TAG: latest

permissions:
  contents: read  # Allows reading files from the repository
  packages: write  # Allows pushing images to the GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase IMAGE_NAME
        run: echo "IMAGE_NAME_LOWER=${{ github.repository }} | tr '[:upper:]' '[:lower:]'" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.IMAGE_TAG }}
